server:
  port: 10000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.10.10:3306/bank?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: dachuang-work
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    base-url: http://192.168.10.10:9411/ #zipkin服务器的地址
    # 关闭服务发现，苟泽spring cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web #设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1 #设置抽样采集率为100% 默认0.1 即10%
